# Generated by Django 5.1.6 on 2025-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('AI Engineer', 'AI Engineer'), ('Data Science', 'Data Science'), ('Data Analytics', 'Data Analytics'), ('Python Engineering', 'Python Engineering'), ('Investment Analytics', 'Investment Analytics'), ('Stuff', 'Stuff')], max_length=50),
        ),
    ]
