# Generated by Django 5.1.6 on 2025-03-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='number',
        ),
    ]
